### ISSUE TITLE
SLIM available as terminal bash command line program ?

### ISSUE THREAD

**Issue by Grelot** [yoann-dufresne/amplicon_pipeline#18]
Hi,

I'm interesting to use SLIM but as a linux bash command line based tool (not the web app) 

Is it possible ?

Thanks and congratulations for your work,
Pierre

**Comment by yoann-dufresne** [comment]
Hi Pierre,

I'm very sorry but no.
SLIM is a GUI and a webserver oriented for biologist scared about command lines.

But all the tools wrapped into SLIM are available in command line.
In fact, SLIM is "only" a command line formatter.

If your problem is that you want to submit your job on a SLIM server using command line, it is possible but not documented.
For now, I'm maintaining the software but I'm not adding new features.
Maybe a new engineer in the project will document and update the http interaction with the server.

Yoann

**Comment by Grelot** [comment]
thank you for this information
